### ISSUE TITLE
Publish a new version of this library that depends on `@rescript/react` rather than `reason-react`

### ISSUE THREAD

**Issue by JasoonS** [ahrefs/melange-recharts#38]

**Comment by liubko** [comment]
Hi, we in Ahrefs kinda stuck with reason-react for now. I suggest you install it from this branch or can fork
```
"@ahrefs/bs-recharts": "git+ssh://git@github.com:ahrefs/bs-recharts#rescript",
```

**Comment by JasoonS** [comment]
Thanks, no problem - will give that a try.

**Comment by Minnozz** [comment]
I've created a fork of this package that uses the new ReScript syntax and depends on `rescript`: https://github.com/Minnozz/rescript-recharts

**Comment by jchavarri** [comment]
Thanks for your interest. The bindings are now compatible with [Melange](http://melange.re/), and the version of reason-react [published in opam](https://opam.ocaml.org/packages/reason-react/). As there are alternative solutions to support ReScript already mentioned in the comments above, I am going to close the issue optimistically.
